name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DJANGO_SETTINGS_MODULE: ecom_demo.settings
  PYTHONUNBUFFERED: 1

jobs:
  build_unit_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django

    - name: Run migrations
      run: python manage.py migrate

    - name: Run unit tests
      run: pytest
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 'False'
        ALLOWED_HOSTS: 'localhost,127.0.0.1'

  e2e_tests:
    needs: build_unit_tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium pytest-selenium
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Run migrations
      run: python manage.py migrate

    - name: Start Django server
      run: |
        python manage.py runserver 0.0.0.0:8000 &> server.log &
        echo $! > server.pid
        sleep 5  # Give server time to start
        cat server.log
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 'True'
        ALLOWED_HOSTS: 'localhost,127.0.0.1,0.0.0.0'

    - name: Run E2E tests
      run: |
        cd ecom_demo
        pytest e2e_tests/ -v

    - name: Stop Django server
      if: always()
      run: kill $(cat server.pid) || true

    - name: Upload server logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: server-logs
        path: server.log
        retention-days: 5