# .github/workflows/django_ci.yml

name: Django CI

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  build_unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
    - name: Run Django migrations
      run: python manage.py migrate
      working-directory: ./

    - name: Run Unit Tests
      run: pytest 
      working-directory: ./

  e2e_tests:
    needs: build_unit_tests 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install Chromium for Selenium
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Run Django migrations
      run: python manage.py migrate
      working-directory: ./

    - name: Start Django development server
      run: |
        nohup python manage.py runserver 0.0.0.0:8000 & # Start server in background
        echo $! > server.pid # Save process ID
      working-directory: ./

    - name: Wait for Django server to be ready
      run: |
        for i in $(seq 1 10); do
          curl -f http://localhost:8000/ && break
          echo "Waiting for Django server... ($i/10)"
          sleep 5
        done
      working-directory: ./

    - name: Run End-to-End Tests (Selenium)
      run: |
          cd ecom_demo
          pytest e2e_tests/
    - name: Stop Django development server
      if: always()
      run: kill $(cat server.pid)
      working-directory: ./

    - name: Upload Failed Test Screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: e2e-failed-screenshots-${{ github.run_id }}
        path: ./test_debug/
        retention-days: 5
