name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DJANGO_SETTINGS_MODULE: ecom_demo.settings
  PYTHONUNBUFFERED: 1
  SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }} 
  DEBUG: 'False'                               
  ALLOWED_HOSTS: 'localhost,127.0.0.1'        

jobs:
  build_unit_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django

    - name: Run migrations
      run: python manage.py migrate

    - name: Run unit tests
      run: pytest products/tests.py 
     
  e2e_tests:
    needs: build_unit_tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium pytest-selenium
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Run migrations
      run: python manage.py migrate

    - name: Start Django server
      run: |
        python manage.py runserver 0.0.0.0:8000 &> server.log &
        echo $! > server.pid
        sleep 5  # Give server time to start
        cat server.log
      
    - name: Wait for Django server to be ready
      run: |
        for i in $(seq 1 10); do
          curl -f http://localhost:8000/ && break
          echo "Waiting for Django server... ($i/10)"
          sleep 5
        done
      working-directory: ./

    - name: Run E2E tests
      run: |
        cd ecom_demo
        pytest e2e_tests/ -v

    - name: Stop Django server
      if: always()
      run: kill $(cat server.pid) || true

    - name: Upload Failed Test Screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: e2e-failed-screenshots-${{ github.run_id }}
        path: ./test_debug/
        retention-days: 5